import Navbar from "../components/Navbar";

const Home = () => {
    return (
        <>
            <Navbar />
            <div className="z-10">
                <h1>Welcome to the Home Page</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam voluptatem accusamus blanditiis exercitationem velit pariatur modi repellendus, dolorem mollitia maiores quod illum perferendis impedit eum nihil eaque vel neque recusandae?</p>
            </div>
        </>
    );
};

export default Home;